### ISSUE TITLE
Missing `gratatouille-processor` artifact on Maven central

### ISSUE THREAD

**Issue by arnav-grabtaxi** [GradleUp/gratatouille#6]
Hi, I'm trying to use Gratatouille to build a plugin using the recommended approach as per the project README. Here's the `build.gradle.kts` for the `plugin-implementation` module:

```groovy
plugins {
    id("org.jetbrains.kotlin.jvm")
    alias(libs.plugins.ksp.plugin)
    alias(libs.plugins.gratatouille.implementation)
    alias(libs.plugins.kotlin.serialization.plugin)
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)
    implementation(libs.ksp.gradle.plugin)
}
```

Since `gratatouille-processor` and `gratatouille-core` are added as dependencies automatically [here](https://github.com/GradleUp/gratatouille/blob/b68f4d3d80485a05bcf3c32ae26af04747a1d56d/gratatouille-gradle-plugin/src/main/kotlin/gratatouille/gradle/GratatouilleImplementationPlugin.kt#L12), the build is failing due to a missing artifact on Maven central:

```
Could not determine the dependencies of task ':plugin:implementation:kspKotlin'.
> Could not resolve all task dependencies for configuration ':plugin:implementation:kspKotlinProcessorClasspath'.
   > Could not find com.gradleup.gratatouille:gratatouille-processor:0.0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/gradleup/gratatouille/gratatouille-processor/0.0.1/gratatouille-processor-0.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/gradleup/gratatouille/gratatouille-processor/0.0.1/gratatouille-processor-0.0.1.pom
     Required by:
         project :plugin:implementation

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Looks like `configureLib` has not been called correctly in [`gratatouille-process/build.gradle.kts`](https://github.com/GradleUp/gratatouille/blob/b68f4d3d80485a05bcf3c32ae26af04747a1d56d/gratatouille-processor/build.gradle.kts), unlike [`gratatouille-core/build.gradle.kts`](https://github.com/GradleUp/gratatouille/blob/b68f4d3d80485a05bcf3c32ae26af04747a1d56d/gratatouille-core/build.gradle.kts).

**Comment by martinbonnin** [comment]
Wooops. Sorry about that, good find! Fix is [here](https://github.com/GradleUp/gratatouille). This week is a bit packed but I'll do a release this week end.
