### ISSUE TITLE
Update gradle-build-action to v3

### ISSUE THREAD

**Issue by LouisCAD** [GradleUp/gratatouille#9]
Hello,

We're currently using v2, and as you can see, it can take a awful long time to cleanup in case of a workflow cancellation.

<img width="1092" alt="Screenshot 2024-07-22 at 22 51 24" src="https://github.com/user-attachments/assets/efc66e13-000e-44c0-b65a-01f9b3d3a126">

Link: https://github.com/GradleUp/gratatouille/actions/runs/10048147226/job/27771471974

I don't know if it's fixed in v3, but I don't see myself reporting this issue while not being on a recent version of [gradle-build-action](https://github.com/gradle/gradle-build-action).

**Comment by martinbonnin** [comment]
SGTM, the version should really be a hash actually, I'll [pin](https://github.com/martinbonnin/pin-github-actions) it

**Comment by LouisCAD** [comment]
We might also want to skip the workflow when the README has been edited

**Comment by martinbonnin** [comment]
https://github.com/GradleUp/gratatouille/pull/10 for the update of the actions.

Re: skipping the workflow I agree this is technically better but would rather have a remote build cache making this an (almost) no-op vs writing yaml...
